// IMPORTANT !!!
// Do not edit this file by hand!
//
// This code is generated by fp-ts-routing-gen (https://github.com/scarf/fp-ts-routing-gen)
// To update the generated code run change 'src/lib/routes.input' and run:
//
//   $ fp-ts-routing-gen --input 'src/lib/routes.input' --out 'src/lib/routes.ts'

import {pipe} from 'fp-ts/function';
import * as O from 'fp-ts/Option';
import * as Routing from 'fp-ts-routing';
import * as t from 'io-ts';

import * as ReturnToT from './returnTo';

type Index = {tag: 'Index'};
type Components = {tag: 'Components'};
type Feedback = {tag: 'Feedback'};
type Login = {tag: 'Login'; returnTo?: ReturnToT.t};
type Register = {tag: 'Register'; email?: string; returnTo?: ReturnToT.t};
type ResetPasswordRequest = {tag: 'ResetPasswordRequest'};
type ResetPasswordConfirm = {tag: 'ResetPasswordConfirm'; token: string};
type Dashboard = {tag: 'Dashboard'};
type SettingsAccount = {tag: 'SettingsAccount'};
type AppDashboard = {tag: 'AppDashboard'; app: string};
type AppEndpoints = {tag: 'AppEndpoints'; app: string};
type AppSubs = {tag: 'AppSubs'; app: string};
type AppLogs = {tag: 'AppLogs'; app: string};
type AppSettingsKeys = {tag: 'AppSettingsKeys'; app: string};
type AppSettingsMembers = {tag: 'AppSettingsMembers'; app: string};
type AppSettingsGeneral = {tag: 'AppSettingsGeneral'; app: string};
type AppSettingsBilling = {tag: 'AppSettingsBilling'; app: string};
type NotFound = {tag: 'NotFound'};

export type Route =
  | Index
  | Components
  | Feedback
  | Login
  | Register
  | ResetPasswordRequest
  | ResetPasswordConfirm
  | Dashboard
  | SettingsAccount
  | AppDashboard
  | AppEndpoints
  | AppSubs
  | AppLogs
  | AppSettingsKeys
  | AppSettingsMembers
  | AppSettingsGeneral
  | AppSettingsBilling
  | NotFound;

export type RouteTag = Route['tag'];

export const match =
  <R>(matcher: {
    Index: (r: Index) => R;
    Components: (r: Components) => R;
    Feedback: (r: Feedback) => R;
    Login: (r: Login) => R;
    Register: (r: Register) => R;
    ResetPasswordRequest: (r: ResetPasswordRequest) => R;
    ResetPasswordConfirm: (r: ResetPasswordConfirm) => R;
    Dashboard: (r: Dashboard) => R;
    SettingsAccount: (r: SettingsAccount) => R;
    AppDashboard: (r: AppDashboard) => R;
    AppEndpoints: (r: AppEndpoints) => R;
    AppSubs: (r: AppSubs) => R;
    AppLogs: (r: AppLogs) => R;
    AppSettingsKeys: (r: AppSettingsKeys) => R;
    AppSettingsMembers: (r: AppSettingsMembers) => R;
    AppSettingsGeneral: (r: AppSettingsGeneral) => R;
    AppSettingsBilling: (r: AppSettingsBilling) => R;
    NotFound: (r: NotFound) => R;
  }) =>
  (route: Route): R => {
    switch (route.tag) {
      case 'Index':
        return matcher.Index(route);
      case 'Components':
        return matcher.Components(route);
      case 'Feedback':
        return matcher.Feedback(route);
      case 'Login':
        return matcher.Login(route);
      case 'Register':
        return matcher.Register(route);
      case 'ResetPasswordRequest':
        return matcher.ResetPasswordRequest(route);
      case 'ResetPasswordConfirm':
        return matcher.ResetPasswordConfirm(route);
      case 'Dashboard':
        return matcher.Dashboard(route);
      case 'SettingsAccount':
        return matcher.SettingsAccount(route);
      case 'AppDashboard':
        return matcher.AppDashboard(route);
      case 'AppEndpoints':
        return matcher.AppEndpoints(route);
      case 'AppSubs':
        return matcher.AppSubs(route);
      case 'AppLogs':
        return matcher.AppLogs(route);
      case 'AppSettingsKeys':
        return matcher.AppSettingsKeys(route);
      case 'AppSettingsMembers':
        return matcher.AppSettingsMembers(route);
      case 'AppSettingsGeneral':
        return matcher.AppSettingsGeneral(route);
      case 'AppSettingsBilling':
        return matcher.AppSettingsBilling(route);
      case 'NotFound':
        return matcher.NotFound(route);
    }
  };

const index: Route = {tag: 'Index'};
const components: Route = {tag: 'Components'};
const feedback: Route = {tag: 'Feedback'};
const login = (returnTo?: ReturnToT.t): Route => ({
  tag: 'Login',
  returnTo,
});
const register = (email?: string, returnTo?: ReturnToT.t): Route => ({
  tag: 'Register',
  email,
  returnTo,
});
const resetPasswordRequest: Route = {tag: 'ResetPasswordRequest'};
const resetPasswordConfirm = (token: string): Route => ({
  tag: 'ResetPasswordConfirm',
  token,
});
const dashboard: Route = {tag: 'Dashboard'};
const settingsAccount: Route = {tag: 'SettingsAccount'};
const appDashboard = (app: string): Route => ({
  tag: 'AppDashboard',
  app,
});
const appEndpoints = (app: string): Route => ({
  tag: 'AppEndpoints',
  app,
});
const appSubs = (app: string): Route => ({
  tag: 'AppSubs',
  app,
});
const appLogs = (app: string): Route => ({
  tag: 'AppLogs',
  app,
});
const appSettingsKeys = (app: string): Route => ({
  tag: 'AppSettingsKeys',
  app,
});
const appSettingsMembers = (app: string): Route => ({
  tag: 'AppSettingsMembers',
  app,
});
const appSettingsGeneral = (app: string): Route => ({
  tag: 'AppSettingsGeneral',
  app,
});
const appSettingsBilling = (app: string): Route => ({
  tag: 'AppSettingsBilling',
  app,
});
const notFound: Route = {tag: 'NotFound'};

export const Route = {
  index,
  components,
  feedback,
  login,
  register,
  resetPasswordRequest,
  resetPasswordConfirm,
  dashboard,
  settingsAccount,
  appDashboard,
  appEndpoints,
  appSubs,
  appLogs,
  appSettingsKeys,
  appSettingsMembers,
  appSettingsGeneral,
  appSettingsBilling,
  notFound,
};

const indexMatch = Routing.end;
const componentsMatch = Routing.lit('components').then(Routing.end);
const feedbackMatch = Routing.lit('feedback').then(Routing.end);
const loginMatch = Routing.lit('login')
  .then(
    // Optional query properties
    // @reference: https://github.com/gcanti/fp-ts-routing/issues/59#issuecomment-800801913
    Routing.query(
      t.exact(
        t.partial({
          returnTo: t.string,
        }),
      ),
    ),
  )
  .then(Routing.end);
const registerMatch = Routing.lit('register')
  .then(
    // Optional query properties
    // @reference: https://github.com/gcanti/fp-ts-routing/issues/59#issuecomment-800801913
    Routing.query(
      t.exact(
        t.partial({
          email: t.string,
          returnTo: t.string,
        }),
      ),
    ),
  )
  .then(Routing.end);
const resetPasswordRequestMatch = Routing.lit('reset-password').then(
  Routing.end,
);
const resetPasswordConfirmMatch = Routing.lit('reset-password')
  .then(Routing.str('token'))

  .then(Routing.end);
const dashboardMatch = Routing.lit('dashboard').then(Routing.end);
const settingsAccountMatch = Routing.lit('settings')
  .then(Routing.lit('account'))

  .then(Routing.end);
const appDashboardMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('dashboard'))

  .then(Routing.end);
const appEndpointsMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('endpoints'))

  .then(Routing.end);
const appSubsMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('subscriptions'))

  .then(Routing.end);
const appLogsMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('logs'))

  .then(Routing.end);
const appSettingsKeysMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('settings'))
  .then(Routing.lit('keys'))

  .then(Routing.end);
const appSettingsMembersMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('settings'))
  .then(Routing.lit('members'))

  .then(Routing.end);
const appSettingsGeneralMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('settings'))
  .then(Routing.lit('general'))

  .then(Routing.end);
const appSettingsBillingMatch = Routing.lit('app')
  .then(Routing.str('app'))
  .then(Routing.lit('settings'))
  .then(Routing.lit('billing'))

  .then(Routing.end);
const notFoundMatch = Routing.lit('404').then(Routing.end);

export const Match = {
  index: indexMatch,
  components: componentsMatch,
  feedback: feedbackMatch,
  login: loginMatch,
  register: registerMatch,
  resetPasswordRequest: resetPasswordRequestMatch,
  resetPasswordConfirm: resetPasswordConfirmMatch,
  dashboard: dashboardMatch,
  settingsAccount: settingsAccountMatch,
  appDashboard: appDashboardMatch,
  appEndpoints: appEndpointsMatch,
  appSubs: appSubsMatch,
  appLogs: appLogsMatch,
  appSettingsKeys: appSettingsKeysMatch,
  appSettingsMembers: appSettingsMembersMatch,
  appSettingsGeneral: appSettingsGeneralMatch,
  appSettingsBilling: appSettingsBillingMatch,
  notFound: notFoundMatch,
};

const router = Routing.zero<Route>()
  .alt(Match.index.parser.map(() => Route.index))
  .alt(Match.components.parser.map(() => Route.components))
  .alt(Match.feedback.parser.map(() => Route.feedback))
  .alt(
    Match.login.parser.map(({returnTo}) =>
      Route.login(ReturnToT.parse(returnTo)),
    ),
  )
  .alt(
    Match.register.parser.map(({email, returnTo}) =>
      Route.register(email, ReturnToT.parse(returnTo)),
    ),
  )
  .alt(Match.resetPasswordRequest.parser.map(() => Route.resetPasswordRequest))
  .alt(
    Match.resetPasswordConfirm.parser.map(({token}) =>
      Route.resetPasswordConfirm(token),
    ),
  )
  .alt(Match.dashboard.parser.map(() => Route.dashboard))
  .alt(Match.settingsAccount.parser.map(() => Route.settingsAccount))
  .alt(Match.appDashboard.parser.map(({app}) => Route.appDashboard(app)))
  .alt(Match.appEndpoints.parser.map(({app}) => Route.appEndpoints(app)))
  .alt(Match.appSubs.parser.map(({app}) => Route.appSubs(app)))
  .alt(Match.appLogs.parser.map(({app}) => Route.appLogs(app)))
  .alt(Match.appSettingsKeys.parser.map(({app}) => Route.appSettingsKeys(app)))
  .alt(
    Match.appSettingsMembers.parser.map(({app}) =>
      Route.appSettingsMembers(app),
    ),
  )
  .alt(
    Match.appSettingsGeneral.parser.map(({app}) =>
      Route.appSettingsGeneral(app),
    ),
  )
  .alt(
    Match.appSettingsBilling.parser.map(({app}) =>
      Route.appSettingsBilling(app),
    ),
  )
  .alt(Match.notFound.parser.map(() => Route.notFound));

export const parse = (path: string): Route =>
  Routing.parse(router, Routing.Route.parse(path), Route.notFound);

export const parseO = (path: string): O.Option<Route> =>
  Routing.parse(router.map(O.some), Routing.Route.parse(path), O.none);

export const format = (route: Route): string =>
  pipe(
    route,
    match<string>({
      Index: () => Routing.format(Match.index.formatter, {}),
      Components: () => Routing.format(Match.components.formatter, {}),
      Feedback: () => Routing.format(Match.feedback.formatter, {}),
      Login: ({returnTo}) =>
        Routing.format(Match.login.formatter, {
          returnTo: ReturnToT.format(returnTo),
        }),
      Register: ({email, returnTo}) =>
        Routing.format(Match.register.formatter, {
          email,
          returnTo: ReturnToT.format(returnTo),
        }),
      ResetPasswordRequest: () =>
        Routing.format(Match.resetPasswordRequest.formatter, {}),
      ResetPasswordConfirm: ({token}) =>
        Routing.format(Match.resetPasswordConfirm.formatter, {token}),
      Dashboard: () => Routing.format(Match.dashboard.formatter, {}),
      SettingsAccount: () =>
        Routing.format(Match.settingsAccount.formatter, {}),
      AppDashboard: ({app}) =>
        Routing.format(Match.appDashboard.formatter, {app}),
      AppEndpoints: ({app}) =>
        Routing.format(Match.appEndpoints.formatter, {app}),
      AppSubs: ({app}) => Routing.format(Match.appSubs.formatter, {app}),
      AppLogs: ({app}) => Routing.format(Match.appLogs.formatter, {app}),
      AppSettingsKeys: ({app}) =>
        Routing.format(Match.appSettingsKeys.formatter, {app}),
      AppSettingsMembers: ({app}) =>
        Routing.format(Match.appSettingsMembers.formatter, {app}),
      AppSettingsGeneral: ({app}) =>
        Routing.format(Match.appSettingsGeneral.formatter, {app}),
      AppSettingsBilling: ({app}) =>
        Routing.format(Match.appSettingsBilling.formatter, {app}),
      NotFound: () => Routing.format(Match.notFound.formatter, {}),
    }),
  );
