name: 'Mirror'

on: 
  push:
    branches:
      - master

jobs:
  push_mirror:
    name: 'Notify Subilo'

    runs-on: ubuntu-18.04

    steps:
    - name: Notify Subilo
      shell: bash
      run: |
        curl -d '{ "name": "therssproject" }' \
          -H "Authorization: $TOKEN" \
          -H "Content-Type: application/json" \
          -X POST "$WEBHOOK"
      env:
        WEBHOOK: ${{ secrets.deploy_webhook }}
        TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
